### ISSUE TITLE
Server 500 Error when Logging In

### ISSUE THREAD

**Issue by simonv3** [suoinguon/slack-backup#2]
Following all the instructions in the README.md, when attempting to log in to the website I get a server 500 error without any other logs:

```
2015-01-12T12:33:24.673513+00:00 heroku[router]: at=info method=GET path="/slack-oauth/login" host=fathomless-chamber-4493.herokuapp.com request_id=ed09a08b-cd52-48c6-8cf6-4a31c6358a5c fwd="123.25.13.174" dyno=web.1 connect=14ms service=390ms status=500 bytes=210
```

**Comment by suoinguon** [comment]
This is usually because you missed this step:
https://github.com/suoinguon/slack-backup#get-your-slack-client_id-and-client_secret

**Comment by simonv3** [comment]
I had the client ID and the client Secret set up properly - it was something to do with my session. Though I don't think it was this, a similar error happened when I was logged in as admin.

**Comment by suoinguon** [comment]
Can you go to settings.py and change DEBUG = True to see the trace?

or you can change the admin email into yours: 

    ADMINS = (('Fountainhead', 'hong@vietnamdevelopers.com'))

so that it will send trace to your email (make sure you add sendgrid plugin into your heroku app)

**Comment by simonv3** [comment]
That's what I did, and I was able to figure out what was going wrong (then)

These are the changes I made to make it a bit easier to debug on both the local and heroku.

https://github.com/simonv3/slack-backup/compare/suoinguon:master...master

**Comment by suoinguon** [comment]
That's cool :)

**Comment by brianjking** [comment]
I'm receiving this error despite following all of the steps -- any leads? I have enabled debug and can send you the crash page as a screenshot? Help! Thanks! @suoinguon
